const config = {
    port: process.env.PORT || 4000,
    patterns: [
        "images/patterns/arrow.png",
        "images/patterns/blackout.png",
        "images/patterns/cross.png",
        "images/patterns/Heart.jpg",
        "images/patterns/L.png",
        "images/patterns/mini.png",
        "images/patterns/peace.png",
        "images/patterns/rows.png",
        "images/patterns/S.png",
        "images/patterns/upsdownl.png",
        "images/patterns/y.png",
        "images/patterns/X.png"
    ],
    strings: [
        "Throws something",
        "Kills a student (FREE SQUARE)",
        "Yells at a student",
        "Lecture about being late",
        "Hits someone with something",
        "Pizza and beer!",
        "Caaaaake",
        "Gets political",
        "'I hate this author'",
        "'you're paying my medicare'",
        "'you should do this in X lines of code'",
        "Makes a student cry",
        "someone calls him 'Father bill'",
        "complains about students outside",
        "'That will be on the test'",
        "complains about canvas",
        "Something about the final",
        "Questions existance",
        "Someone asks a question that he doesn't understand",
        "he (thinks) he knows everything",
        "Yells about phones",
        "Public shaming",
        "Says he hates a student",
        "threatens to beat a student",
        "'why do I do this'",
        "mentions being a pilot",
        "Random student walks into the class",
        "something something Elon Musk",
        "mentions that google is the anti-christ",
        "That one story he's told 100000x but it changes ever so slightly",
        "Praises Apple as if it were a god",
        "anything about IBM",
        "Strokes his ponytail",
        "mentions the dean",
        "says how much he loves his wife",
        "something about Stackoverflow ",
        "'bug in the language'",
        "'read the book' or 'it/this is in be book'"
    ]
}

module.exports = config;
