const config = {
    port: process.env.PORT || 4000,
    patterns:[
        "images/patterns/arrow.png",
        "images/patterns/blackout.png",
        "images/patterns/cross.png",
        "images/patterns/Heart.jpg",
        "images/patterns/L.png",
        "images/patterns/mini.png",
        "images/patterns/peace.png",
        "images/patterns/rows.png",
        "images/patterns/S.png",
        "images/patterns/upsdownl.png",
        "images/patterns/y.png",
        "images/patterns/X.png"
    ],
    strings: [
        "Throws something",
        "Kills a student",
        "Yells at Matthew",
        "Yi Onni gets up",
        "Yi Onni gets a cookie",
        "Lecture about being late",
        "Hits somone with something",
        "Pizza and beer!",
        "Caaaaake",
        "Gets political",
        "'I hate this author'",
        "'you're paying my medicare'",
        "'you should do this in X lines of code'",
        "Makes a student cry",
        "someone calls him 'Father bill'",
        "complains about students outside",
        "'That will be on the test'",
        "complains about canvas",
        "Something about the final",
        "Questions existance",
        "Someone asks a question that he doesn't understand",
        "VIDEOS",
        "Yells about phones",
        "Public shaming",
        "Says he hates a student",
        "threatens to beat a student",
        "'why do I do this'",
        "Hits Brandon with a redvine",
        "mentions being a pilot",
        "Random student walks into the class"]
}

module.exports = config;